### PR TITLE
Cypher tests

### PR DESCRIPTION
**Pull request by farleyknight**

### CODE REVIEW

**Comment by samsquire** [comment]
Change the query to

MATCH (actor)-[:ACTED_IN]->(wallstreet:Movie {title: 'Wall Street'}) RETURN actor

Then it shall parse. Graph shall have inside it the parsed data

**Comment by farleyknight** [comment]
Okay, I updated the query, but still not seeing any parsed tokens? I see a couple of booleans, individual characters, and the original statement, but that's it..

Screen Shot 2022-05-18 at 12 37 20 PM

**Comment by farleyknight** [comment]
@samsquire I think I figured it out. I think it needs to be lowercase `match` and `return`. That gets me a little bit further :)

**Comment by samsquire** [comment]
match (actor)-[:ACTED_IN]->(wallstreet:Movie {title: 'Wall Street'}) return actor

Works. It's case sensitive. I'll change the parser to be case insensitive.

**Comment by farleyknight** [comment]
> match (actor)-[:ACTED_IN]->(wallstreet:Movie {title: 'Wall Street'}) return actor
> 
> Works. It's case sensitive. I'll change the parser to be case insensitive.

Awesome! Yea, I actually have never used the Cypher language before, so a lot of this is still new to me. I would imagine it's a pretty complex language to parse.

**Comment by samsquire** [comment]
Probably shouldn't hast done that but I pushed to this branch

**Comment by samsquire** [comment]
I realised that my approach to lowering the identifiers is probably a bad one as the Movie label is  also lowercased. So either I update the parser code to lowercase every cypher keyword or think of another method to support lowercase keywords.

**Comment by samsquire** [comment]
> > match (actor)-[:ACTED_IN]->(wallstreet:Movie {title: 'Wall Street'}) return actor
> > Works. It's case sensitive. I'll change the parser to be case insensitive.
> 
> Awesome! Yea, I actually have never used the Cypher language before, so a lot of this is still new to me. I would imagine it's a pretty complex language to parse.

The language is similar to SQL, it's quite straightforward to parse! But if you want different direction arrows and all one line is more complicated. I learned parsing from [LLVM compiler examplecode.](https://llvm.org/docs/tutorial/MyFirstLanguageFrontend/index.html)

**Comment by samsquire** [comment]
You've seen the parser's output code, you should understand part of the Cypher executor in client.py Graph().

**Comment by farleyknight** [comment]
Is there a good guide on the language as a whole? I was curious and found this document: https://neo4j.com/docs/cypher-refcard/current/

I would like to write tests for all of the existing cases it can handle, and possibly a few that it does not yet handle. Is the `MATCH/RETURN` grammar the main/only one that it handles now?

**Comment by samsquire** [comment]
It also supports MERGE statement 
Which looks like this and updates the graph.

```
merge (person:Person {'name': 'Samuel'})-[:FRIEND]->(tasya:Person {'name': 'Tasya'})
```

I need to add where clause support

That documentation you linked is how I learned Cypher

**Comment by samsquire** [comment]
I updated my previous comment. I didn't learn cypher from that refcard but that refcard looks good I learned the basics of cypher from the link I posted

**Comment by samsquire** [comment]
The parser doesn't parse paths or assignments or LIMIT or WHERE or any of the other features of cypher.

**Comment by farleyknight** [comment]
> The parser doesn't parse paths or assignments or LIMIT or WHERE or any of the other features of cypher.

I might try and add support for `LIMIT` and `WHERE` at some point. Want to get a few more tests written first, but definitely looking to add functionality, if you're cool with it :)

**Comment by samsquire** [comment]
That's fine with me. I'm happy someone is reading and understanding my code. Any feedback would be appreciated.

**Pull request merged**
